Numpy

In [1]:
#Import Numpy Library
import numpy as np

In [2]:
#Creating the numpy array
a = np.array([1,9,8])
a

array([1, 9, 8])

In [3]:
b = np.array([(5,1,4),(7,2,9)])
b

array([[5, 1, 4],
       [7, 2, 9]])

In [4]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
d = np.ones(3)
d

array([1., 1., 1.])

In [6]:
d = np.ones(3,dtype = np.int16)
d

array([1, 1, 1], dtype=int16)

#---------------------------------------------------Inspecting the array#----------------------------------------------------

In [7]:
#Inspecting the array
len(a)

3

In [8]:
b.shape

(2, 3)

In [9]:
b.ndim

2

In [10]:
b.size

6

#---------------------------------------------------Subsetting the array-----------------------------------------------------

In [11]:

a[2]

8

In [12]:
a[0:2]

array([1, 9])

In [13]:
a[a>3]

array([9, 8])

In [14]:
b[1,2] 

9

In [15]:
b[0:2,1]

array([1, 2])

In [16]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
x[0:16:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

#---------------------------------------------------#Array Manupilations-----------------------------------------------------

In [18]:

np.insert(a, 1, 5)

array([1, 5, 9, 8])

In [19]:
np.delete(a,[1])

array([1, 8])

In [20]:
np.concatenate((a,d),axis=0)

array([1, 9, 8, 1, 1, 1])

In [21]:
np.vstack((b,b)) 

array([[5, 1, 4],
       [7, 2, 9],
       [5, 1, 4],
       [7, 2, 9]])

In [22]:
np.hstack((b,b)) 

array([[5, 1, 4, 5, 1, 4],
       [7, 2, 9, 7, 2, 9]])

In [23]:
a.sort()
a

array([1, 8, 9])

In [24]:
print("a")
print(a)
print("b")
print(b)

a
[1 8 9]
b
[[5 1 4]
 [7 2 9]]


In [25]:
i = np.transpose(b)
i

array([[5, 7],
       [1, 2],
       [4, 9]])

In [26]:
np.concatenate((b,b),axis=0)

array([[5, 1, 4],
       [7, 2, 9],
       [5, 1, 4],
       [7, 2, 9]])

In [27]:
np.concatenate((b,b),axis=1)

array([[5, 1, 4, 5, 1, 4],
       [7, 2, 9, 7, 2, 9]])

In [28]:
z = np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.hsplit(z,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
np.hsplit(z,np.array([1, 3]))

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [31]:
np.vsplit(z,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

#-----------------------------------------------------#Array Operations-----------------------------------------------------

In [32]:

a.sum()

18

In [33]:
a.min()

1

In [34]:
a.mean()

6.0

In [35]:
b.max(axis=0) 

array([7, 2, 9])

In [36]:
b.max(axis=1) 

array([5, 9])

In [37]:
g = a - b 
g

array([[-4,  7,  5],
       [-6,  6,  0]])

In [38]:
np.subtract(a,b) 

array([[-4,  7,  5],
       [-6,  6,  0]])

In [39]:
a / b 

array([[0.2       , 8.        , 2.25      ],
       [0.14285714, 4.        , 1.        ]])

In [40]:
np.sqrt(a)

array([1.        , 2.82842712, 3.        ])

In [41]:
np.sin(a)

array([0.84147098, 0.98935825, 0.41211849])

In [42]:
a == d

array([ True, False, False])

In [43]:
np.array_equal(a, b)

False